Set-Alias -Name g -Value git
Set-Alias -Name allc -Value all-contributors
Set-Alias -Name notepad -Value notepad++
Set-Alias -Name gti -Value git
Set-Alias -Name dc -Value Docker-Compose-Alias
Set-Alias -Name favware -Value Set-Favware-Location
Set-Alias -Name sky -Value Set-SkyraProject-Location
Set-Alias -Name saph -Value Set-SapphireDev-Location
Set-Alias -Name nu -Value Start-Npm-Upgrade
Set-Alias -Name y -Value yarn
Set-Alias -Name rmf -Value Remove-Files-Recursively-Forced
Set-Alias -Name rimraf -Value Remove-Files-Recursively-Forced
Set-Alias -Name lsd -Value Launch-Switch-Dvr
Set-Alias -Name neofetch -Value winfetch
Set-Alias -Name yarn2 -Value Start-Yarn3
Set-Alias -Name yarn3 -Value Start-Yarn3
Set-Alias -Name sharing -Value Set-Sharing-Resolution
Set-Alias -Name working -Value Set-Working-Resolution
Set-Alias -Name lavs -Value Set-Lavs-Location
Set-Alias -Name script -Value Run-Script
Set-Alias -Name scripts -Value Run-Script
