Set-Alias -Name notepad -Value notepad++
Set-Alias -Name dc -Value Docker-Compose-Alias
Set-Alias -Name nu -Value Start-Npm-Upgrade
Set-Alias -Name y -Value yarn
Set-Alias -Name rmf -Value Remove-Files-Recursively-Forced
Set-Alias -Name rimraf -Value Remove-Files-Recursively-Forced
Set-Alias -Name lsd -Value Launch-Switch-Dvr
Set-Alias -Name neofetch -Value winfetch
Set-Alias -Name sharing -Value Set-Sharing-Resolution
Set-Alias -Name working -Value Set-Working-Resolution
